### ISSUE TITLE
About results

### ISSUE THREAD

**Issue by duzhenjiang113** [cihanongun/LPMNet#1]
Hi, I think your work is very interesting, and could you please tell me how to get the final visual rendering :-)

**Comment by cihanongun** [comment]
Hi, thanks. I have modified the StructureNet Visualization scripts to visualize my outputs.
https://github.com/daerduoCarey/structurenet/tree/master/viz_blender

**Comment by duzhenjiang113** [comment]
thanks, i'll try it.

**Comment by duzhenjiang113** [comment]
And i also have a question about the model.  Why do you add the generative model between the part feature extractor and global feature extractor? It seems that the generative model can be added in front of the decoder.

**Comment by cihanongun** [comment]
The generative model generates part features so we can generate parts besides the global model. By this way, we can replace a part, combine different generated parts or generate a missing part. If you add it in front of the decoder, you can only generate global shapes, not parts.

**Comment by duzhenjiang113** [comment]
> The generative model generates part features so we can generate parts besides the global model. By this way, we can replace a part, combine different generated parts or generate a missing part. If you add it in front of the decoder, you can only generate global shapes, not parts.

Thanks
